In [70]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [71]:
df1=pd.read_csv('https://raw.githubusercontent.com/UNCG-DAISY/Tiny_Gesture/main/data/jump_set.csv')
df2=pd.read_csv('https://raw.githubusercontent.com/UNCG-DAISY/Tiny_Gesture/main/data/other_set.csv')
df3=pd.read_csv('https://raw.githubusercontent.com/UNCG-DAISY/Tiny_Gesture/main/data/run_set.csv')
df4=pd.read_csv('https://raw.githubusercontent.com/UNCG-DAISY/Tiny_Gesture/main/data/squat_set.csv')
df5=pd.read_csv('https://raw.githubusercontent.com/UNCG-DAISY/Tiny_Gesture/main/data/walk_set.csv')

In [72]:
df1['gesture']=1
df2['gesture']=2
df3['gesture']=3
df4['gesture']=4
df5['gesture']=5

In [73]:
df=pd.concat([df1,df2,df3,df4,df5],axis=0)

In [74]:
df.head()

aX     aY     aZ      gX      gY       gZ  gesture
0 -0.868 -0.676  0.086 -60.364  62.622   97.839        1
1 -0.777 -0.677  0.109 -58.716  79.651  104.553        1
2 -0.737 -0.622  0.066 -40.039  61.951  102.356        1
3 -0.727 -0.403  0.017 -14.832  33.936   95.459        1
4 -0.689 -0.249 -0.048   6.348  14.771   86.975        1

In [75]:
d=pd.get_dummies(df,columns=['gesture'])

In [76]:
d

aX     aY     aZ      gX      gY       gZ  gesture_1  gesture_2  \
0     -0.868 -0.676  0.086 -60.364  62.622   97.839          1          0   
1     -0.777 -0.677  0.109 -58.716  79.651  104.553          1          0   
2     -0.737 -0.622  0.066 -40.039  61.951  102.356          1          0   
3     -0.727 -0.403  0.017 -14.832  33.936   95.459          1          0   
4     -0.689 -0.249 -0.048   6.348  14.771   86.975          1          0   
...      ...    ...    ...     ...     ...      ...        ...        ...   
11895 -0.983 -0.046 -0.069   2.747  -0.122   -0.793          0          0   
11896 -0.985 -0.043 -0.071   3.174  -1.038   -0.671          0          0   
11897 -0.984 -0.042 -0.061   2.991  -0.549   -0.244          0          0   
11898 -0.983 -0.050 -0.063   2.808  -0.732    0.122          0          0   
11899 -0.977 -0.043 -0.061   3.479  -1.038   -0.244          0          0   

       gesture_3  gesture_4  gesture_5  
0              0          0          0  
1              0          0          0  
2              0          0          0  
3              0          0          0  
4              0          0          0  
...          ...        ...        ...  
11895          0          0          1  
11896          0          0          1  
11897          0          0          1  
11898          0          0          1  
11899          0          0          1  

[59500 rows x 11 columns]

In [77]:
from sklearn.model_selection import train_test_split

In [78]:
x=d[['aX','aY','aZ','gX','gY','gZ']]
y=d[['gesture_1','gesture_2','gesture_3','gesture_4','gesture_5']]

In [79]:
x.shape

(59500, 6)

In [80]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [81]:
y_train

gesture_1  gesture_2  gesture_3  gesture_4  gesture_5
7720          0          0          1          0          0
5489          1          0          0          0          0
2065          0          0          0          1          0
6982          0          0          0          1          0
3940          0          0          0          0          1
...         ...        ...        ...        ...        ...
6743          0          0          0          0          1
2458          0          0          0          1          0
860           1          0          0          0          0
3895          0          1          0          0          0
8822          0          0          0          0          1

[39865 rows x 5 columns]

In [82]:
from sklearn.preprocessing import MinMaxScaler

In [83]:
sc=MinMaxScaler()

In [84]:
sc.fit(x_train)

MinMaxScaler()

In [85]:
x_train=sc.transform(x_train)

In [86]:
x_test=sc.transform(x_test)

In [87]:
y_test

gesture_1  gesture_2  gesture_3  gesture_4  gesture_5
10289          1          0          0          0          0
2128           0          0          1          0          0
10880          1          0          0          0          0
3894           0          0          1          0          0
9311           1          0          0          0          0
...          ...        ...        ...        ...        ...
9318           0          0          0          1          0
10411          0          0          0          1          0
4226           1          0          0          0          0
4185           1          0          0          0          0
9037           1          0          0          0          0

[19635 rows x 5 columns]

In [88]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout


In [89]:
model=Sequential()
model.add(Dense(512,activation='relu',input_dim=6))
model.add(Dense(256,activation='relu'))
model.add(Dense(128,activation='relu'))

model.add(Dense(5,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [90]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_18 (Dense)             (None, 512)               3584      
_________________________________________________________________
dense_19 (Dense)             (None, 256)               131328    
_________________________________________________________________
dense_20 (Dense)             (None, 128)               32896     
_________________________________________________________________
dense_21 (Dense)             (None, 5)                 645       
Total params: 168,453
Trainable params: 168,453
Non-trainable params: 0
_________________________________________________________________


In [91]:
model.fit(x=x_train,y=y_train,epochs=5)

Epoch 1/5
1246/1246 [==============================] - 2s 1ms/step - loss: 1.3400 - accuracy: 0.3811
Epoch 2/5
1246/1246 [==============================] - 2s 1ms/step - loss: 0.9173 - accuracy: 0.6062
Epoch 3/5
1246/1246 [==============================] - 1s 1ms/step - loss: 0.7574 - accuracy: 0.6786
Epoch 4/5
1246/1246 [==============================] - 1s 1ms/step - loss: 0.7087 - accuracy: 0.6981
Epoch 5/5
1246/1246 [==============================] - 1s 1ms/step - loss: 0.6687 - accuracy: 0.7187


In [115]:
p=model.predict(x_test)

In [117]:
p

array([[1.0318755e-01, 6.2393486e-11, 9.9052116e-02, 2.9685481e-02,
        7.6807487e-01],
       [1.3546899e-01, 9.2167333e-08, 6.1842275e-01, 2.1498294e-01,
        3.1125264e-02],
       [4.8057503e-01, 1.8536809e-07, 1.5045093e-01, 6.6284738e-02,
        3.0268911e-01],
       ...,
       [5.2118379e-01, 4.7178132e-06, 2.0096977e-01, 2.2116075e-01,
        5.6680974e-02],
       [3.7965614e-02, 4.2999068e-06, 9.6198428e-01, 9.4900923e-07,
        4.4884368e-05],
       [3.3994865e-01, 1.5666355e-06, 3.0243054e-01, 2.7843210e-01,
        7.9187259e-02]], dtype=float32)

In [119]:
pp=p.argmax(axis=1)

In [120]:
j=y_test.values

In [121]:
jj=j.argmax(axis=1)

In [122]:
len(jj[jj==1])

3867

In [123]:
from sklearn.metrics import confusion_matrix

In [124]:
print(confusion_matrix(jj,pp))

[[2762   19  709  295  202]
 [   3 3854    9    1    0]
 [ 605   20 2689  397  168]
 [ 831   28  604 2378   66]
 [ 292  314  110   10 3269]]
